# Pandas

References: https://www.kaggle.com/rajacsp/pandas-cheatsheet-125-exercises https://www.kaggle.com/grroverpr/pandas-cheatsheet 
            https://www.kaggle.com/lavanyashukla01/pandas-numpy-python-cheatsheet https://www.kaggle.com/learn/pandas https://learn.datacamp.com/courses/data-manipulation-with-pandas https://www.stats.govt.nz/large-datasets/csv-files-for-download/

The Pandas library is built on NumPy and provides easy-to-use data structures and data analysis tools for the Python programming language.

### Pandas Data Structures
1.Series: A one-dimensional labeled array,capable of holding any data type.One of the main differences between Pandas Series and NumPy ndarrays is that you can assign an index label to each element in the Pandas Series.

pd.Series(data, index)

2.Dataframe:Pandas DataFrames are two-dimensional data structures with labeled rows and columns, that can hold many data types.

### Input/Output

......

### Different ways of creating DataFrame

.............

In [3]:
import pandas as pd
df=pd.read_csv('enterprise-survey.csv')
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [4]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...

.head() returns the first few(mostly 5)

In [5]:
df.tail() #displays last few rows of the dataframe.

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32445 entries, 0 to 32444
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         32445 non-null  int64
 1   Industry_aggregation_NZSIOC  32445 non-null  object
 2   Industry_code_NZSIOC         32445 non-null  object
 3   Industry_name_NZSIOC         32445 non-null  object
 4   Units                        32445 non-null  object
 5   Variable_code                32445 non-null  object
 6   Variable_name                32445 non-null  object
 7   Variable_category            32445 non-null  object
 8   Value                        32445 non-null  object
 9   Industry_code_ANZSIC06       32445 non-null  object
dtypes: int64(1), object(9)
memory usage: 2.5+ MB

.info() shows info on each of the columns such as data types and missing values.

In [7]:
df.shape #rows,column

(32445, 10)

In [8]:
df.describe() #calculates a few summary statistics for each column

               Year
count  32445.000000
mean    2016.000000
std        2.000031
min     2013.000000
25%     2014.000000
50%     2016.000000
75%     2018.000000
max     2019.000000

In [9]:
df.index

RangeIndex(start=0, stop=32445, step=1)

In [10]:
df.columns #gives all the column names

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [11]:
df.values #df.values returns a numpy array with the underlying data of the DataFrame, without any index or columns names.

array([[2019, 'Level 1', '99999', ..., 'Financial performance',
        '728,239',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2019, 'Level 1', '99999', ..., 'Financial performance',
        '643,809',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       [2019, 'Level 1', '99999', ..., 'Financial performance', '62,924',
        'ANZSIC06 divisions A-S (excluding classes K6330, L6711, O7552, O760, O771, O772, S9540, S9601, S9602, and S9603)'],
       ...,
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '12',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'],
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '5',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119'],
       [2013, 'Level 3', 'ZZ11', ..., 'Financial ratios', '46',
        'ANZSIC06 groups C111, C112, C113, C114, C115, C116, C117, C118, and C119']],
      dtype=object)

### Sorting and subsetting

In [12]:
df.sort_index() #sort the dataframe through the index.

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [13]:
df.sort_values('Industry_code_NZSIOC',ascending=True)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
27835,2013,Level 1,99999,All industries,Dollars,H35,Surplus per employee count,Financial ratios,33800,ANZSIC06 divisions A-S (excluding classes K633...
27836,2013,Level 1,99999,All industries,Percentage,H36,Current ratio,Financial ratios,77,ANZSIC06 divisions A-S (excluding classes K633...
27837,2013,Level 1,99999,All industries,Percentage,H37,Quick ratio,Financial ratios,69,ANZSIC06 divisions A-S (excluding classes K633...
27838,2013,Level 1,99999,All industries,Percentage,H39,Return on equity,Financial ratios,10,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
23172,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H39,Return on equity,Financial ratios,17,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
23171,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,28,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
23170,2015,Level 3,ZZ11,Food Product Manufacturing,Percentage,H37,Quick ratio,Financial ratios,74,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4631,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,28,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [14]:
df.sort_values(['Industry_code_NZSIOC','Year'],ascending=False) #sorting by multiple values

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
4599,2019,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H01,Total income,Financial performance,"45,225","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4600,2019,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H02,Sales of goods not further processed,Financial performance,"1,594","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4601,2019,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H03,Sales of other goods and services,Financial performance,"43,116","ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4602,2019,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,307,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4603,2019,Level 3,ZZ11,Food Product Manufacturing,Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,4,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
...,...,...,...,...,...,...,...,...,...,...
27836,2013,Level 1,99999,All industries,Percentage,H36,Current ratio,Financial ratios,77,ANZSIC06 divisions A-S (excluding classes K633...
27837,2013,Level 1,99999,All industries,Percentage,H37,Quick ratio,Financial ratios,69,ANZSIC06 divisions A-S (excluding classes K633...
27838,2013,Level 1,99999,All industries,Percentage,H39,Return on equity,Financial ratios,10,ANZSIC06 divisions A-S (excluding classes K633...
27839,2013,Level 1,99999,All industries,Percentage,H40,Return on total assets,Financial ratios,3,ANZSIC06 divisions A-S (excluding classes K633...
27840,2013,Level 1,99999,All industries,Percentage,H41,Liabilities structure,Financial ratios,31,ANZSIC06 divisions A-S (excluding classes K633...

In [15]:
df.sort_values('Year',ascending=True)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
29349,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H09,Interest and donations,Financial performance,36,"ANZSIC06 groups C245, C246, and C249"
29350,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H10,Indirect taxes,Financial performance,9,"ANZSIC06 groups C245, C246, and C249"
29351,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H11,Depreciation,Financial performance,72,"ANZSIC06 groups C245, C246, and C249"
29352,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H12,Salaries and wages paid,Financial performance,908,"ANZSIC06 groups C245, C246, and C249"
...,...,...,...,...,...,...,...,...,...,...
3092,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H09,Interest and donations,Financial performance,"21,211",ANZSIC06 division K
3093,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H10,Indirect taxes,Financial performance,116,ANZSIC06 division K
3094,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H11,Depreciation,Financial performance,997,ANZSIC06 division K
3042,2019,Level 3,JJ11,Information Media Services,Dollars (millions),H30,Total equity and liabilities,Financial position,"5,448","ANZSIC06 groups J541, J542, J551, J552, J561, ..."
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...

In [16]:
df.sort_values(['Industry_code_NZSIOC','Year'],ascending=[False,True]) #sort first column by descending order and Year by ascending order.

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
32409,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H01,Total income,Financial performance,36411,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32410,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H02,Sales of goods not further processed,Financial performance,2808,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32411,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H03,Sales of other goods and services,Financial performance,33253,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32412,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,C,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32413,2013,Level 3,ZZ11,Food product manufacturing,Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,C,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
...,...,...,...,...,...,...,...,...,...,...
26,2019,Level 1,99999,All industries,Percentage,H36,Current ratio,Financial ratios,76,ANZSIC06 divisions A-S (excluding classes K633...
27,2019,Level 1,99999,All industries,Percentage,H37,Quick ratio,Financial ratios,68,ANZSIC06 divisions A-S (excluding classes K633...
28,2019,Level 1,99999,All industries,Percentage,H39,Return on equity,Financial ratios,13,ANZSIC06 divisions A-S (excluding classes K633...
29,2019,Level 1,99999,All industries,Percentage,H40,Return on total assets,Financial ratios,4,ANZSIC06 divisions A-S (excluding classes K633...
30,2019,Level 1,99999,All industries,Percentage,H41,Liabilities structure,Financial ratios,33,ANZSIC06 divisions A-S (excluding classes K633...

In [17]:
#Subsetting columns
df['Year']

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
32440    2013
32441    2013
32442    2013
32443    2013
32444    2013
Name: Year, Length: 32445, dtype: int64

In [18]:
df.Year

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
32440    2013
32441    2013
32442    2013
32443    2013
32444    2013
Name: Year, Length: 32445, dtype: int64

In [19]:
columns_selected=['Year','Units']
df[columns_selected]

       Year               Units
0      2019  Dollars (millions)
1      2019  Dollars (millions)
2      2019  Dollars (millions)
3      2019  Dollars (millions)
4      2019  Dollars (millions)
...     ...                 ...
32440  2013          Percentage
32441  2013          Percentage
32442  2013          Percentage
32443  2013          Percentage
32444  2013          Percentage

[32445 rows x 2 columns]

In [20]:
df[['Year','Units']]

       Year               Units
0      2019  Dollars (millions)
1      2019  Dollars (millions)
2      2019  Dollars (millions)
3      2019  Dollars (millions)
4      2019  Dollars (millions)
...     ...                 ...
32440  2013          Percentage
32441  2013          Percentage
32442  2013          Percentage
32443  2013          Percentage
32444  2013          Percentage

[32445 rows x 2 columns]

In [21]:
#Subsetting rows
df[df['Year']>2018]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
4630,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H37,Quick ratio,Financial ratios,85,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4631,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,28,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4632,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H39,Return on equity,Financial ratios,18,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4633,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H40,Return on total assets,Financial ratios,8,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4634,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H41,Liabilities structure,Financial ratios,47,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [22]:
df[df['Units']=='Percentage']

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
26,2019,Level 1,99999,All industries,Percentage,H36,Current ratio,Financial ratios,76,ANZSIC06 divisions A-S (excluding classes K633...
27,2019,Level 1,99999,All industries,Percentage,H37,Quick ratio,Financial ratios,68,ANZSIC06 divisions A-S (excluding classes K633...
28,2019,Level 1,99999,All industries,Percentage,H39,Return on equity,Financial ratios,13,ANZSIC06 divisions A-S (excluding classes K633...
29,2019,Level 1,99999,All industries,Percentage,H40,Return on total assets,Financial ratios,4,ANZSIC06 divisions A-S (excluding classes K633...
30,2019,Level 1,99999,All industries,Percentage,H41,Liabilities structure,Financial ratios,33,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [23]:
df['Year'][df['Units']=='Dollars (millions)']

0        2019
1        2019
2        2019
3        2019
4        2019
         ...
32432    2013
32433    2013
32434    2013
32435    2013
32436    2013
Name: Year, Length: 25508, dtype: int64

In [24]:
df[['Year','Industry_code_NZSIOC','Units']][df['Units']=='Dollars (millions)']

       Year Industry_code_NZSIOC               Units
0      2019                99999  Dollars (millions)
1      2019                99999  Dollars (millions)
2      2019                99999  Dollars (millions)
3      2019                99999  Dollars (millions)
4      2019                99999  Dollars (millions)
...     ...                  ...                 ...
32432  2013                 ZZ11  Dollars (millions)
32433  2013                 ZZ11  Dollars (millions)
32434  2013                 ZZ11  Dollars (millions)
32435  2013                 ZZ11  Dollars (millions)
32436  2013                 ZZ11  Dollars (millions)

[25508 rows x 3 columns]

In [25]:
df[(df['Year']>2018)& (df['Units']=='Percentage')]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
26,2019,Level 1,99999,All industries,Percentage,H36,Current ratio,Financial ratios,76,ANZSIC06 divisions A-S (excluding classes K633...
27,2019,Level 1,99999,All industries,Percentage,H37,Quick ratio,Financial ratios,68,ANZSIC06 divisions A-S (excluding classes K633...
28,2019,Level 1,99999,All industries,Percentage,H39,Return on equity,Financial ratios,13,ANZSIC06 divisions A-S (excluding classes K633...
29,2019,Level 1,99999,All industries,Percentage,H40,Return on total assets,Financial ratios,4,ANZSIC06 divisions A-S (excluding classes K633...
30,2019,Level 1,99999,All industries,Percentage,H41,Liabilities structure,Financial ratios,33,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
4630,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H37,Quick ratio,Financial ratios,85,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4631,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,28,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4632,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H39,Return on equity,Financial ratios,18,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4633,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H40,Return on total assets,Financial ratios,8,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4634,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H41,Liabilities structure,Financial ratios,47,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [26]:
df[(df['Year']>2018)| (df['Units']=='Percentage')] #Logical OR

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [27]:
#Subsetting using isin(),categorical values
year_2019=df['Year'].isin([2019])
year_2019

0         True
1         True
2         True
3         True
4         True
         ...
32440    False
32441    False
32442    False
32443    False
32444    False
Name: Year, Length: 32445, dtype: bool

In [28]:
df[year_2019]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
4630,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H37,Quick ratio,Financial ratios,85,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4631,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,28,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4632,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H39,Return on equity,Financial ratios,18,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4633,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H40,Return on total assets,Financial ratios,8,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
4634,2019,Level 3,ZZ11,Food Product Manufacturing,Percentage,H41,Liabilities structure,Financial ratios,47,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [29]:
df[df['Industry_aggregation_NZSIOC'].isin(['Level1','Level 3'])]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
62,2019,Level 3,AA11,Horticulture and Fruit Growing,Dollars (millions),H01,Total income,Financial performance,"4,788","ANZSIC06 groups A011, A012, and A013"
63,2019,Level 3,AA11,Horticulture and Fruit Growing,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"4,471","ANZSIC06 groups A011, A012, and A013"
64,2019,Level 3,AA11,Horticulture and Fruit Growing,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,132,"ANZSIC06 groups A011, A012, and A013"
65,2019,Level 3,AA11,Horticulture and Fruit Growing,Dollars (millions),H07,Non-operating income,Financial performance,185,"ANZSIC06 groups A011, A012, and A013"
66,2019,Level 3,AA11,Horticulture and Fruit Growing,Dollars (millions),H08,Total expenditure,Financial performance,"3,981","ANZSIC06 groups A011, A012, and A013"
...,...,...,...,...,...,...,...,...,...,...
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

### Adding a new column to a dataframe

In [30]:
df['Day']=df.Value*2
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06,Day
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...,"728,239728,239"
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...,"643,809643,809"
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...,"62,92462,924"
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...,"21,50521,505"
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...,"634,710634,710"
...,...,...,...,...,...,...,...,...,...,...,...
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",5252
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",4040
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",1212
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",55
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ...",4646

<b>We can also create a new column by using a list, df.insert(index,'Columnname',value),df.assign(columnname='value')</b>

### Summary Statistics

In [32]:
df.Year.min()

2013

In [33]:
df.Year.max()

2019

In [35]:
df.Year.agg(min)

2013

In [43]:
import numpy as np
agg_func=[min,max,sum]
df[['Value','Industry_code_NZSIOC']].agg(agg_func)

,Value,Industry_code_NZSIOC
min,-1,99999
max,S,ZZ11
sum,"728,239643,80962,92421,505634,71035,2507,45820...",9999999999999999999999999999999999999999999999...

In [46]:
#cumulative statistics
df.Value.cumsum()

0                                                  728,239
1                                           728,239643,809
2                                     728,239643,80962,924
3                               728,239643,80962,92421,505
4                        728,239643,80962,92421,505634,710
                               ...
32440    728,239643,80962,92421,505634,71035,2507,45820...
32441    728,239643,80962,92421,505634,71035,2507,45820...
32442    728,239643,80962,92421,505634,71035,2507,45820...
32443    728,239643,80962,92421,505634,71035,2507,45820...
32444    728,239643,80962,92421,505634,71035,2507,45820...
Name: Value, Length: 32445, dtype: object

In [47]:
df.Value.cummin()

0        728,239
1        643,809
2         62,924
3         21,505
4         21,505
          ...
32440         -1
32441         -1
32442         -1
32443         -1
32444         -1
Name: Value, Length: 32445, dtype: object

In [53]:
#df.Year.drop_duplicates()

In [54]:
df.Year.value_counts()

2015    4635
2014    4635
2013    4635
2019    4635
2018    4635
2017    4635
2016    4635
Name: Year, dtype: int64

In [56]:
numbers=[2,6,8,1]
for index,num in enumerate(numbers,7):
    print(index,num)

7 2
8 6
9 8
10 1